"""g1: card assignee, priority, due_date, labels

Revision ID: 97984d3b6f54
Revises: d21351a6ac89
Create Date: 2026-06-25 22:40:50.803504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97984d3b6f54'
down_revision: Union[str, Sequence[str], None] = 'd21351a6ac89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), server_default='slate', nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_board_id'), 'labels', ['board_id'], unique=False)
    op.create_table('card_labels',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'label_id')
    )
    op.add_column('cards', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('cards', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_cards_assignee_id'), 'cards', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'cards', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_assignee_id_fkey', 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_assignee_id'), table_name='cards')
    op.drop_column('cards', 'due_date')
    op.drop_column('cards', 'priority')
    op.drop_column('cards', 'assignee_id')
    op.drop_table('card_labels')
    op.drop_index(op.f('ix_labels_board_id'), table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
