"""g3: issue_type, story_points, wip_limit

Revision ID: d24c3316f954
Revises: 7dac116bc944
Create Date: 2026-06-26 01:22:30.432685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24c3316f954'
down_revision: Union[str, Sequence[str], None] = '7dac116bc944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('issue_type', sa.String(length=20), server_default='task', nullable=False))
    op.add_column('cards', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('lists', sa.Column('wip_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'wip_limit')
    op.drop_column('cards', 'story_points')
    op.drop_column('cards', 'issue_type')
    # ### end Alembic commands ###
